# Generated by Django 2.2.3 on 2019-08-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
                ('sidewall', models.IntegerField()),
                ('rim', models.IntegerField()),
            ],
        ),
    ]
